language: java
dist: bionic
sudo: required
services:
  - docker
jdk:
  - openjdk11
git:
  depth: false
script:
  - mvn clean install
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'